# Generated by Django 4.1 on 2022-11-04 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.IntegerField(null=True)),
                ('evento', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=400)),
                ('fecha_de_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio del proyecto')),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('En Planificacion', 'En Planificacion'), ('En Curso', 'En Curso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='En Planificacion', max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
