<<<<<<< HEAD
# Generated by Django 4.1 on 2022-09-30 15:58
=======
# Generated by Django 4.1 on 2022-10-16 23:36
>>>>>>> origin/desarrollo

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '__first__'),
        ('permisos', '__first__'),
        ('Sprint', '__first__'),
        ('UserStories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
                ('roles', models.ManyToManyField(to='permisos.rolesdesistema')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=400)),
                ('fecha_de_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio del proyecto')),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('En Planificacion', 'En Planificacion'), ('En Curso', 'En Curso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='En Planificacion', max_length=20)),
<<<<<<< HEAD
                ('miembros', models.ManyToManyField(related_name='set_miembros', to='Usuarios.usuario')),
                ('roles', models.ManyToManyField(to='permisos.rolesdesistema')),
                ('scrumMaster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
                ('sprint', models.ManyToManyField(to='Sprint.sprint')),
                ('tipo_us', models.ManyToManyField(to='UserStories.tipouserstory')),
                ('usuario_roles', models.ManyToManyField(to='Proyectos.rolusuario')),
=======
            ],
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> origin/desarrollo
            ],
        ),
    ]
