# Generated by Django 4.1 on 2022-09-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('Proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='miembros',
            field=models.ManyToManyField(to='Usuarios.usuario'),
        ),
    ]
