# Generated by Django 4.1 on 2022-11-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('Proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolusuario',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario'),
        ),
    ]
