# Generated by Django 4.1 on 2022-09-15 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('Proyectos', '0002_proyecto_miembros'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='scrumMaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='miembros',
            field=models.ManyToManyField(related_name='set_miembros', to='Usuarios.usuario'),
        ),
    ]
