# Generated by Django 4.1 on 2022-10-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='motivo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
