# Generated by Django 4.1 on 2022-11-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.IntegerField(null=True)),
                ('evento', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='historial',
            field=models.ManyToManyField(to='Proyectos.historia'),
        ),
    ]
