# Generated by Django 4.1 on 2022-09-21 20:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0003_proyecto_scrummaster_alter_proyecto_miembros'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tipos_us',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='user_stories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
    ]
