# Generated by Django 4.1 on 2022-09-23 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0005_alter_rolesdesistema_options'),
        ('Usuarios', '0001_initial'),
        ('Proyectos', '0003_proyecto_scrummaster_alter_proyecto_miembros'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='roles',
            field=models.ManyToManyField(to='permisos.rolesdesistema'),
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=400)),
                ('miembros', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyectos.proyecto')),
                ('rol', models.ManyToManyField(to='permisos.rolesdesistema')),
            ],
        ),
    ]
