# Generated by Django 4.1 on 2022-09-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0004_proyecto_tipos_us_proyecto_user_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20, verbose_name='Estado actual del Proyecto'),
        ),
    ]
