# Generated by Django 4.1 on 2022-09-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0004_proyecto_roles_rolusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolusuario',
            old_name='miembros',
            new_name='miembro',
        ),
        migrations.RenameField(
            model_name='rolusuario',
            old_name='rol',
            new_name='roles',
        ),
        migrations.RemoveField(
            model_name='rolusuario',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='rolusuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='rolusuario',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuario_roles',
            field=models.ManyToManyField(to='Proyectos.rolusuario'),
        ),
    ]
