# Generated by Django 4.1 on 2022-11-04 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0004_proyecto_motivo'),
        ('Proyectos', '0005_alter_historia_evento'),
    ]

    operations = [
    ]
