# Generated by Django 4.1 on 2022-09-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0003_remove_tipouserstory_prefijo'),
        ('Proyectos', '0005_alter_proyecto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='tipos_us',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipos_us',
            field=models.ManyToManyField(related_name='set_tipos_us', to='UserStories.tipouserstory'),
        ),
    ]
