# Generated by Django 4.1 on 2022-09-22 21:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0008_alter_proyecto_tipos_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='user_stories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None),
        ),
    ]
