# Generated by Django 4.1 on 2022-09-23 16:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0013_alter_proyecto_tipos_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tipos_us',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
    ]
