# Generated by Django 4.1 on 2022-09-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0006_alter_proyecto_estado'),
        ('Proyectos', '0014_alter_proyecto_tipos_us'),
    ]

    operations = [
    ]
