# Generated by Django 4.1 on 2022-09-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0015_merge_20220925_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='tipos_us',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='user_stories',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('En Planificacion', 'En Planificacion'), ('En Curso', 'En Curso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='En Planificacion', max_length=20),
        ),
    ]
