# Generated by Django 4.1 on 2022-09-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0009_userstories_id_proyecto'),
        ('Proyectos', '0016_remove_proyecto_tipos_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tipo_us',
            field=models.ManyToManyField(to='UserStories.tipouserstory'),
        ),
    ]
