# Generated by Django 4.1 on 2022-09-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0018_proyecto_user_stories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='tipo_us',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='user_stories',
        ),
    ]
