# Generated by Django 4.1 on 2022-09-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0015_merge_20220925_1726'),
        ('Proyectos', '0022_proyecto_tipo_us'),
    ]

    operations = [
    ]
