# Generated by Django 4.1 on 2022-09-29 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('Proyectos', '0023_merge_0015_merge_20220925_1726_0022_proyecto_tipo_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolusuario',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario'),
        ),
    ]
