# Generated by Django 4.1 on 2022-09-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0007_sprint_id_proyecto'),
        ('Proyectos', '0023_merge_0015_merge_20220925_1726_0022_proyecto_tipo_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='sprint',
            field=models.ManyToManyField(to='Sprint.sprint'),
        ),
    ]
