# Generated by Django 4.1 on 2022-09-30 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0024_alter_rolusuario_miembro'),
        ('Proyectos', '0024_proyecto_sprint'),
    ]

    operations = [
    ]
