# Generated by Django 4.1 on 2022-10-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sprint', '0001_initial'),
        ('UserStories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='historias',
            field=models.ManyToManyField(blank=True, to='UserStories.userstories'),
        ),
    ]
