# Generated by Django 4.1 on 2022-09-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='estado_sprint',
            field=models.CharField(choices=[('En Planificacion', 'En Planificacion'), ('En Curso', 'En Ejecucion'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='En Planificacion', max_length=20),
        ),
    ]
