# Generated by Django 4.1 on 2022-10-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('Sprint', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='miembros_sprint',
            field=models.ManyToManyField(related_name='set_miembros_sprint', to='Usuarios.usuario'),
        ),
    ]
