# Generated by Django 4.1 on 2022-09-28 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('Sprint', '0002_alter_sprint_estado_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='miembros_sprint',
            field=models.ManyToManyField(related_name='set_miembros_sprint', to='Usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio'),
        ),
    ]
