# Generated by Django 4.1 on 2022-10-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprintmiembros',
            name='capacidad_miembro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
