# Generated by Django 4.1 on 2022-09-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0003_sprint_miembros_sprint_alter_sprint_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='capacidad',
            field=models.IntegerField(null=True, verbose_name='Capacidad en horas'),
        ),
    ]
