# Generated by Django 4.1 on 2022-10-31 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0003_sprint_capacidad_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='capacidad',
            field=models.IntegerField(null=True, verbose_name='Capacidad en horas'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='capacidad_us',
            field=models.IntegerField(default=0),
        ),
    ]
