# Generated by Django 4.1 on 2022-10-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0003_sprint_capacidad_equipo'),
        ('Sprint', '0005_alter_sprintmiembros_capacidad_miembro'),
    ]

    operations = [
    ]
