# Generated by Django 4.1 on 2022-09-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0005_sprint_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
    ]
