# Generated by Django 4.1 on 2022-10-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0006_merge_20221022_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='capacidad',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Capacidad en horas'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='capacidad_us',
            field=models.IntegerField(default=0),
        ),
    ]
