# Generated by Django 4.1 on 2022-11-02 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0003_alter_sprintmiembros_capacidad_miembro'),
        ('Sprint', '0007_alter_sprint_capacidad_alter_sprint_capacidad_us'),
    ]

    operations = [
    ]
