# Generated by Django 4.1 on 2022-09-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0007_sprint_id_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='contador_sprint_activo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='contador_sprint_planificado',
            field=models.IntegerField(null=True),
        ),
    ]
