# Generated by Django 4.1 on 2022-09-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0008_sprint_contador_sprint_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='contador_sprint_activo',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='contador_sprint_planificado',
        ),
    ]
