# Generated by Django 4.1 on 2022-10-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0009_remove_sprint_contador_sprint_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='capacidad_us',
            field=models.IntegerField(default=0),
        ),
    ]
