# Generated by Django 4.1 on 2022-10-15 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('UserStories', '0027_alter_userstories_prioridad'),
        ('Sprint', '0010_sprintmiembros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprintmiembros',
            name='miembro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario'),
        ),
        migrations.RemoveField(
            model_name='sprintmiembros',
            name='us_asignado',
        ),
        migrations.AddField(
            model_name='sprintmiembros',
            name='us_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserStories.userstories'),
        ),
    ]
