# Generated by Django 4.1 on 2022-10-15 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0011_alter_sprintmiembros_miembro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprintmiembros',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sprint.sprint'),
        ),
    ]
