# Generated by Django 4.1 on 2022-10-15 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0025_merge_20220930_0211'),
        ('Sprint', '0012_alter_sprintmiembros_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintmiembros',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyectos.proyecto'),
        ),
    ]
