# Generated by Django 4.1 on 2022-10-16 22:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estados_Kanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('defecto', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Estado_Kanban',
                'verbose_name_plural': 'Estados_Kanban',
            },
        ),
        migrations.CreateModel(
            name='TipoUSerStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'TipoUS',
                'verbose_name_plural': 'TiposUS',
            },
        ),
        migrations.CreateModel(
            name='UserStories',
            fields=[
                ('id_us', models.AutoField(primary_key=True, serialize=False)),
                ('id_proyecto', models.IntegerField(null=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=60)),
                ('comentarios', models.TextField(blank=True, default='')),
                ('horas_estimadas', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('PN', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('PT', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('PS', models.IntegerField(blank=True, default=0)),
                ('Prioridad', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('en_sprint', models.BooleanField(default=False)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserStories.estados_kanban')),
            ],
            options={
                'verbose_name': 'UserStory',
                'verbose_name_plural': 'UserStories',
            },
        ),
    ]
