# Generated by Django 4.1 on 2022-09-30 15:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados_Kanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Estado_Kanban',
                'verbose_name_plural': 'Estados_Kanban',
            },
        ),
        migrations.CreateModel(
            name='TipoUSerStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=80, null=True)),
                ('estados_kanban', models.ManyToManyField(to='UserStories.estados_kanban')),
            ],
            options={
                'verbose_name': 'TipoUS',
                'verbose_name_plural': 'TiposUS',
            },
        ),
        migrations.CreateModel(
            name='UserStories',
            fields=[
                ('id_us', models.AutoField(primary_key=True, serialize=False)),
                ('id_proyecto', models.IntegerField(null=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=60)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], max_length=20)),
                ('comentarios', models.TextField(blank=True, default='')),
                ('horas_estimadas', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('miembro_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserStories.tipouserstory')),
            ],
            options={
                'verbose_name': 'UserStory',
                'verbose_name_plural': 'UserStories',
            },
        ),
    ]
