# Generated by Django 4.1 on 2022-09-16 05:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estados_Kanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Estado_Kanban',
                'verbose_name_plural': 'Estados_Kanban',
            },
        ),
        migrations.CreateModel(
            name='TipoUSerStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('prefijo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, max_length=80)),
                ('estados_kanban', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
            ],
            options={
                'verbose_name': 'TipoUS',
                'verbose_name_plural': 'TiposUS',
            },
        ),
    ]
