<<<<<<< HEAD
# Generated by Django 4.1 on 2022-11-04 16:10
=======
# Generated by Django 4.1 on 2022-11-09 20:13
>>>>>>> desarrollo

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserStories', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstories',
            name='miembro_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='userstories',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserStories.tipouserstory'),
        ),
        migrations.AddField(
            model_name='tipouserstory',
            name='estados_kanban',
            field=models.ManyToManyField(to='UserStories.estados_kanban'),
        ),
        migrations.AddField(
            model_name='historicaluserstories',
            name='estado',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='UserStories.estados_kanban'),
        ),
        migrations.AddField(
            model_name='historicaluserstories',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaluserstories',
            name='miembro_asignado',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='historicaluserstories',
            name='tipo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='UserStories.tipouserstory'),
        ),
    ]
