# Generated by Django 4.1 on 2022-09-20 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('UserStories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStories',
            fields=[
                ('id_us', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=60)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], max_length=20)),
                ('comentarios', models.TextField(blank=True, default='')),
                ('horas_estimadas', models.IntegerField(default=0)),
                ('miembro_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserStories.tipouserstory')),
            ],
            options={
                'verbose_name': 'UserStory',
                'verbose_name_plural': 'UserStories',
            },
        ),
    ]
