# Generated by Django 4.1 on 2022-10-14 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('UserStories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstories',
            name='miembro_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='userstories',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserStories.tipouserstory'),
        ),
        migrations.AddField(
            model_name='tipouserstory',
            name='estados_kanban',
            field=models.ManyToManyField(to='UserStories.estados_kanban'),
        ),
    ]
