# Generated by Django 4.1 on 2022-10-31 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstories',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, max_length=60),
        ),
    ]
