# Generated by Django 4.1 on 2022-10-30 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstories',
            name='horas_trabajadas',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
