# Generated by Django 4.1 on 2022-09-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0003_remove_tipouserstory_prefijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados_kanban',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
