# Generated by Django 4.1 on 2022-10-31 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0003_userstories_horas_trabajadas'),
        ('UserStories', '0003_userstories_motivo_cancelacion'),
    ]

    operations = [
    ]
