# Generated by Django 4.1 on 2022-10-30 20:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserStories', '0003_userstories_horas_trabajadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUserStories',
            fields=[
                ('id_us', models.IntegerField(blank=True, db_index=True)),
                ('id_proyecto', models.IntegerField(null=True)),
                ('nombre', models.CharField(db_index=True, max_length=20)),
                ('descripcion', models.TextField(blank=True, max_length=60)),
                ('comentarios', models.TextField(blank=True, default='')),
                ('horas_estimadas', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('PN', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('PT', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('PS', models.IntegerField(blank=True, default=0)),
                ('Prioridad', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('en_sprint', models.BooleanField(default=False)),
                ('horas_trabajadas', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('estado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='UserStories.estados_kanban')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('miembro_asignado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Usuarios.usuario')),
                ('tipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='UserStories.tipouserstory')),
            ],
            options={
                'verbose_name': 'historical UserStory',
                'verbose_name_plural': 'historical UserStories',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
