# Generated by Django 4.1 on 2022-09-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0004_alter_estados_kanban_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstories',
            name='tipo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
