# Generated by Django 4.1 on 2022-09-25 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0005_alter_userstories_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUS_Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.ManyToManyField(to='UserStories.tipouserstory')),
            ],
        ),
        migrations.AlterField(
            model_name='userstories',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserStories.tipous_proyecto'),
        ),
    ]
