# Generated by Django 4.1 on 2022-10-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('UserStories', '0005_historicaluserstories_actividad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluserstories',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='userstories',
            name='responsable',
        ),
        migrations.AddField(
            model_name='userstories',
            name='responsable',
            field=models.ManyToManyField(blank=True, related_name='responsable', to='Usuarios.usuario'),
        ),
    ]
