# Generated by Django 4.1 on 2022-10-30 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('UserStories', '0006_remove_historicaluserstories_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserstories',
            name='responsable',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='historicaluserstories',
            name='actividad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userstories',
            name='actividad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='userstories',
            name='responsable',
        ),
        migrations.AddField(
            model_name='userstories',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_responsable', to='Usuarios.usuario'),
        ),
    ]
