# Generated by Django 4.1 on 2022-09-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0006_tipous_proyecto_alter_userstories_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstories',
            name='id_proyecto',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
