# Generated by Django 4.1 on 2022-09-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0007_userstories_id_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstories',
            name='id_proyecto',
        ),
    ]
