# Generated by Django 4.1 on 2022-10-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0007_historicaluserstories_responsable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluserstories',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='userstories',
            name='responsable',
        ),
        migrations.AddField(
            model_name='historicaluserstories',
            name='horas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userstories',
            name='horas',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
