# Generated by Django 4.1 on 2022-09-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0008_remove_userstories_id_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstories',
            name='id_proyecto',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
