# Generated by Django 4.1 on 2022-11-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0004_merge_20221031_0232'),
        ('UserStories', '0008_remove_historicaluserstories_responsable_and_more'),
    ]

    operations = [
    ]
