# Generated by Django 4.1 on 2022-11-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0009_merge_20221103_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserstories',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, max_length=60),
        ),
    ]
