# Generated by Django 4.1 on 2022-09-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0010_tipous_proyecto_id_proyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstories',
            name='id_proyecto',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
