# Generated by Django 4.1 on 2022-09-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0011_alter_userstories_id_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipous_proyecto',
            name='id_proyecto',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
