# Generated by Django 4.1 on 2022-09-25 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0012_alter_tipous_proyecto_id_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstories',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserStories.tipouserstory'),
        ),
    ]
