# Generated by Django 4.1 on 2022-09-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0015_alter_userstories_id_proyecto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoUS_Proyecto',
        ),
    ]
