# Generated by Django 4.1 on 2022-09-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0016_delete_tipous_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipouserstory',
            name='estados_kanban',
        ),
        migrations.AddField(
            model_name='tipouserstory',
            name='estados_kanban',
            field=models.ManyToManyField(to='UserStories.estados_kanban'),
        ),
    ]
