# Generated by Django 4.1 on 2022-09-30 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0017_remove_tipouserstory_estados_kanban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstories',
            name='horas_estimadas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
