# Generated by Django 4.1 on 2022-10-07 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0018_alter_userstories_horas_estimadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstories',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserStories.estados_kanban'),
            preserve_default=False,
        ),
    ]
