# Generated by Django 4.1 on 2022-10-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0018_alter_userstories_horas_estimadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='estados_kanban',
            name='defecto',
            field=models.BooleanField(default=False),
        ),
    ]
