# Generated by Django 4.1 on 2022-10-11 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0019_estados_kanban_defecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstories',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='userstories',
            name='PN',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='userstories',
            name='PS',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userstories',
            name='PT',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='userstories',
            name='horas_estimadas',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
