# Generated by Django 4.1 on 2022-10-11 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0019_estados_kanban_defecto'),
        ('UserStories', '0020_alter_userstories_estado'),
    ]

    operations = [
    ]
