# Generated by Django 4.1 on 2022-10-12 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0020_remove_userstories_prioridad_userstories_pn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstories',
            name='horas_estimadas',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
