# Generated by Django 4.1 on 2022-10-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0022_alter_userstories_horas_estimadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstories',
            name='Prioridad',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
