# Generated by Django 4.1 on 2022-10-13 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0024_alter_userstories_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstories',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserStories.estados_kanban'),
        ),
    ]
