# Generated by Django 4.1 on 2022-10-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStories', '0025_userstories_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstories',
            name='en_sprint',
            field=models.BooleanField(default=False),
        ),
    ]
