# Generated by Django 4.1 on 2022-11-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesdeSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('defecto', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, max_length=60)),
                ('permisos', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={
                'permissions': [('_crear_usuario', 'Crear usuario'), ('_eliminar_usuario', 'Eliminar usuario'), ('_acceder_al_sistema', 'Acceder al sistema'), ('_crear_roles', 'Crear roles'), ('_asignar_roles', 'Asignar roles a usuario'), ('_visualizar_roles', 'Visualizar roles a usuario'), ('_eliminar_roles', 'Eliminar roles a usuario'), ('_visualizar_usuario', 'Visualizar usuario del Sistema'), ('_crear_proyecto', 'Crear Proyecto'), ('_editar_proyecto', 'Editar Proyecto'), ('_visualizar_proyecto', 'Visualizar Proyecto'), ('_cancelar_proyecto', 'Cancelar Proyecto'), ('_eliminar_miembros', 'Eliminar miembros de un proyecto'), ('_visualizar_historial_proyecto', 'Visualizar historial del proyecto'), ('_modificar_fecha', 'Modificar fecha de inicio y fin del proyecto'), ('_modificar_estado_proyecto', 'Modificar estado del proyecto'), ('_crear_sprint', 'Crear sprint'), ('_modificar_sprint', 'Modificar sprint'), ('_modificar_estado_sprint', 'Modificar estado de un sprint'), ('_crear_us', 'Crear US'), ('_modificar_us', 'Modificar US'), ('_modificar_estado_us', 'Modificar estado de US'), ('_cancelar_us', 'Cancelar US'), ('_consultar_historial_us', 'Consultar historial de un US'), ('_modificar_backlog', 'Modificar Product Backlog'), ('_modificar_sprint_backlog', 'Modificar Sprint Backlog'), ('_crear_tipos_us', 'Crear tipos de US'), ('_modificar_tipos_us', 'Modificar tipos de US'), ('_visualizar_kanban', 'Visualizar Tabla Kamban'), ('_iniciar_proyecto', 'Iniciar un proyecto'), ('_asignar_us', 'Asignar US'), ('_visualizar_sprint', 'Visualizar Sprint'), ('_visualizar Product Backlog', 'Visualizar Product Backlog')],
            },
        ),
    ]
