# Generated by Django 4.1 on 2022-08-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesdeSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=60)),
                ('permisos', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={
                'permissions': [('crear_usuario', 'Crear usuario'), ('eliminar_usuario', 'Eliminar usuario'), ('crear_roles', 'Crear roles'), ('asignar_roles', 'Asignar roles a usuario'), ('visualizar_usuario', 'Visualizar usuario del Sistema'), ('crear_proyecto', 'Crear Proyecto'), ('editar_proyecto', 'Editar Proyecto'), ('visualizar_proyecto', 'Visualizar Proyecto'), ('cancelar_proyecto', 'Cancelar Proyecto'), ('eliminar_miembros', 'Eliminar miembros de un proyecto'), ('visualizar_historial_proyecto', 'Visualizar historial del proyecto'), ('modificar_fecha', 'Modificar fecha de inicio y fin del proyecto'), ('modificar_estado_proyecto', 'Modificar estado del proyecto'), ('crear_sprint', 'Crear sprint'), ('modificar_sprint', 'Modificar sprint'), ('modificar_estado_sprint', 'Modificar estado de un sprint'), ('crear_us', 'Crear US'), ('modificar_us', 'Modificar US'), ('modificar_estado_us', 'Modificar estado de US'), ('cancelar_us', 'Cancelar US'), ('consultar_historial_us', 'Consultar historial de un US'), ('modificar_backlog', 'Modificar Product Backlog'), ('modificar_sprint_backlog', 'Modificar Sprint Backlog'), ('crear_tipos_us', 'Crear tipos de US'), ('modificar_tipos_us', 'Modificar tipos de US'), ('visualizar_burndown_chart', 'Visualizar Burndown Chart'), ('visualizar_kanban', 'Visualizar Tabla Kamban')],
            },
        ),
    ]
