# Generated by Django 4.1 on 2022-08-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Permisos', '0002_alter_rolesdesistema_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolesdesistema',
            options={'permissions': [('crear_usuario', 'Crear usuario'), ('eliminar_usuario', 'Eliminar usuario'), ('acceder_al_sistema', 'Acceder al sistema'), ('crear_roles', 'Crear roles'), ('asignar_roles', 'Asignar roles a usuario'), ('visualizar_usuario', 'Visualizar usuario del Sistema'), ('crear_proyecto', 'Crear Proyecto'), ('editar_proyecto', 'Editar Proyecto'), ('visualizar_proyecto', 'Visualizar Proyecto'), ('cancelar_proyecto', 'Cancelar Proyecto'), ('eliminar_miembros', 'Eliminar miembros de un proyecto'), ('visualizar_historial_proyecto', 'Visualizar historial del proyecto'), ('modificar_fecha', 'Modificar fecha de inicio y fin del proyecto'), ('modificar_estado_proyecto', 'Modificar estado del proyecto'), ('crear_sprint', 'Crear sprint'), ('modificar_sprint', 'Modificar sprint'), ('modificar_estado_sprint', 'Modificar estado de un sprint'), ('crear_us', 'Crear US'), ('modificar_us', 'Modificar US'), ('modificar_estado_us', 'Modificar estado de US'), ('cancelar_us', 'Cancelar US'), ('consultar_historial_us', 'Consultar historial de un US'), ('modificar_backlog', 'Modificar Product Backlog'), ('modificar_sprint_backlog', 'Modificar Sprint Backlog'), ('crear_tipos_us', 'Crear tipos de US'), ('modificar_tipos_us', 'Modificar tipos de US'), ('visualizar_burndown_chart', 'Visualizar Burndown Chart'), ('visualizar_kanban', 'Visualizar Tabla Kamban')]},
        ),
    ]
