# Generated by Django 4.1 on 2022-09-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0002_alter_rolesdesistema_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesdesistema',
            name='defecto',
            field=models.BooleanField(default=False),
        ),
    ]
